# Generated by Django 5.1.15 on 2026-06-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, verbose_name='IP地址')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('action', models.CharField(max_length=50, verbose_name='操作动作')),
                ('detail', models.JSONField(default=dict, verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'bs_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'bs_system_config',
            },
        ),
        migrations.CreateModel(
            name='AdminRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='rooms.room', verbose_name='自习室')),
            ],
            options={
                'verbose_name': '管理员-自习室绑定',
                'verbose_name_plural': '管理员-自习室绑定',
                'db_table': 'bs_admin_room',
            },
        ),
    ]
