# Generated by Django 5.1.15 on 2026-06-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('checked_in', '已签到'), ('completed', '已完成'), ('cancelled', '已取消'), ('no_show', '爽约')], default='pending', max_length=20, verbose_name='状态')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='取消原因')),
                ('is_temp', models.BooleanField(default=False, verbose_name='临时预约')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'db_table': 'bs_reservation',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WaitQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('notified', '已通知'), ('accepted', '已接受'), ('expired', '已过期'), ('cancelled', '已取消')], default='waiting', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '排队候补',
                'verbose_name_plural': '排队候补',
                'db_table': 'bs_wait_queue',
                'ordering': ['created_at'],
            },
        ),
    ]
