# Generated by Django 5.1.15 on 2026-06-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(verbose_name='变动值')),
                ('balance', models.IntegerField(verbose_name='变动后余额')),
                ('type', models.CharField(choices=[('init', '初始积分'), ('no_show', '爽约'), ('late', '迟到'), ('severe_late', '严重迟到'), ('ghost_occupation', '占座不用'), ('proxy', '代签'), ('disorder', '扰乱秩序'), ('damage', '损坏设施'), ('temp_leave_timeout', '暂离超时'), ('item_left', '物品遗留'), ('streak_7', '连续7天'), ('streak_30', '连续30天'), ('attendance_90', '月出勤率>90%'), ('report_violation', '举报违规'), ('appeal_reversal', '申诉撤销'), ('manual', '手动调整')], max_length=30, verbose_name='变动类型')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='关联业务ID')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'db_table': 'bs_credit_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
