# Generated by Django 5.1.15 on 2026-06-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('attachment', models.FileField(blank=True, upload_to='announcements/', verbose_name='附件')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('scope_type', models.CharField(choices=[('all', '全平台'), ('room', '指定自习室'), ('college', '指定学院')], default='all', max_length=20, verbose_name='发布范围类型')),
                ('scope_value', models.JSONField(blank=True, default=list, help_text='自习室ID列表或学院名称列表', verbose_name='范围值')),
                ('start_time', models.DateTimeField(verbose_name='生效时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'bs_announcement',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
            ],
            options={
                'verbose_name': '公告已读',
                'verbose_name_plural': '公告已读',
                'db_table': 'bs_announcement_read',
            },
        ),
    ]
