# Generated by Django 5.1.15 on 2026-06-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bug', '故障报修'), ('suggestion', '建议'), ('complaint', '投诉')], max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('attachment', models.ImageField(blank=True, upload_to='feedback/', verbose_name='附件')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('reply', models.TextField(blank=True, default='', verbose_name='回复')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='满意度(1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '反馈',
                'verbose_name_plural': '反馈',
                'db_table': 'bs_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
