# Generated by Django 5.1.15 on 2026-06-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='签退时间')),
                ('check_in_method', models.CharField(choices=[('qr', '二维码'), ('face', '人脸识别'), ('manual', '管理员手动'), ('gps', 'GPS定位')], default='qr', max_length=20, verbose_name='签到方式')),
                ('is_ontime', models.BooleanField(default=True, verbose_name='是否准时')),
                ('is_early_leave', models.BooleanField(default=False, verbose_name='是否早退')),
                ('temp_leave_count', models.IntegerField(default=0, verbose_name='暂离次数')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='在座时长(分钟)')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'db_table': 'bs_checkin',
            },
        ),
        migrations.CreateModel(
            name='TempLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_time', models.DateTimeField(verbose_name='离开时间')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='返回时间')),
                ('is_timeout', models.BooleanField(default=False, verbose_name='是否超时')),
            ],
            options={
                'verbose_name': '暂离记录',
                'verbose_name_plural': '暂离记录',
                'db_table': 'bs_temp_leave',
            },
        ),
    ]
