# Generated by Django 5.1.15 on 2026-06-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkin', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='reservations.reservation', verbose_name='关联预约'),
        ),
        migrations.AddField(
            model_name='templeave',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_leaves', to='checkin.checkin', verbose_name='签到记录'),
        ),
    ]
