# Generated by Django 5.1.15 on 2026-06-26 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='入黑原因')),
                ('days', models.IntegerField(default=7, help_text='0=永久', verbose_name='处罚天数')),
                ('started_at', models.DateTimeField(verbose_name='生效时间')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='提前解除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_blacklists', to=settings.AUTH_USER_MODEL, verbose_name='解除人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '黑名单记录',
                'verbose_name_plural': '黑名单记录',
                'db_table': 'bs_blacklist_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('no_show', '爽约'), ('late', '迟到'), ('severe_late', '严重迟到'), ('ghost_occupation', '占座不用'), ('proxy', '代签'), ('disorder', '扰乱秩序'), ('damage', '损坏设施'), ('temp_leave_timeout', '暂离超时'), ('item_left', '物品遗留')], max_length=30, verbose_name='违规类型')),
                ('points_deducted', models.IntegerField(default=0, verbose_name='扣分值')),
                ('description', models.TextField(blank=True, default='', verbose_name='违规描述')),
                ('evidence', models.ImageField(blank=True, upload_to='violations/', verbose_name='证据附件')),
                ('status', models.CharField(choices=[('pending_review', '待审核'), ('confirmed', '已确认'), ('appealed', '申诉中'), ('overturned', '已撤销')], default='pending_review', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_violations', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='reservations.reservation', verbose_name='关联预约')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '违规记录',
                'verbose_name_plural': '违规记录',
                'db_table': 'bs_violation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='申诉理由')),
                ('attachment', models.ImageField(blank=True, upload_to='appeals/', verbose_name='附件')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('partially_approved', '部分通过')], default='pending', max_length=30, verbose_name='状态')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL, verbose_name='申诉人')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='violations.violation', verbose_name='关联违规')),
            ],
            options={
                'verbose_name': '申诉记录',
                'verbose_name_plural': '申诉记录',
                'db_table': 'bs_appeal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['user', 'created_at'], name='bs_violatio_user_id_e07b1c_idx'),
        ),
    ]
