# Generated by Django 5.1.15 on 2026-06-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='自习室名称')),
                ('building', models.CharField(max_length=100, verbose_name='所属建筑')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('capacity', models.IntegerField(default=0, verbose_name='总座位数')),
                ('room_type', models.CharField(choices=[('silent', '静音区'), ('normal', '普通区'), ('discussion', '讨论区'), ('computer', '电脑区')], default='normal', max_length=20, verbose_name='区域类型')),
                ('status', models.CharField(choices=[('open', '开放'), ('closed', '关闭'), ('maintenance', '维护中')], default='open', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('image', models.ImageField(blank=True, upload_to='rooms/', verbose_name='图片')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='每日开放时间')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='每日关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自习室',
                'verbose_name_plural': '自习室',
                'db_table': 'bs_room',
                'ordering': ['building', 'floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='时段名称')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='rooms.room', verbose_name='所属自习室')),
            ],
            options={
                'verbose_name': '时段模板',
                'verbose_name_plural': '时段模板',
                'db_table': 'bs_timeslot',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20, verbose_name='座位编号')),
                ('row', models.IntegerField(default=0, verbose_name='网格行')),
                ('col', models.IntegerField(default=0, verbose_name='网格列')),
                ('seat_type', models.CharField(choices=[('normal', '普通座'), ('power', '带电源座'), ('booth', '卡座'), ('standing', '站立桌')], default='normal', max_length=20, verbose_name='座位类型')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='设施标签')),
                ('status', models.CharField(choices=[('available', '可用'), ('maintenance', '维修中'), ('reserved', '预留')], default='available', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='rooms.room', verbose_name='所属自习室')),
            ],
            options={
                'verbose_name': '座位',
                'verbose_name_plural': '座位',
                'db_table': 'bs_seat',
                'ordering': ['room', 'row', 'col'],
                'unique_together': {('room', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='SpecialSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='开放时间')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('is_closed', models.BooleanField(default=False, verbose_name='全天闭馆')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='原因')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_schedules', to='rooms.room', verbose_name='自习室')),
            ],
            options={
                'verbose_name': '特殊日程',
                'verbose_name_plural': '特殊日程',
                'db_table': 'bs_special_schedule',
                'unique_together': {('room', 'date')},
            },
        ),
    ]
