# Generated by Django 5.1.15 on 2026-06-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('reservation', '预约通知'), ('checkin', '签到提醒'), ('violation', '违规通知'), ('blacklist', '黑名单通知'), ('appeal', '申诉结果'), ('system', '系统通知'), ('announcement', '公告')], default='system', max_length=30, verbose_name='分类')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='已读')),
                ('channels', models.JSONField(default=list, verbose_name='发送渠道')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'bs_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
